#!/bin/bash

yellow=`tput setaf 3`
reset=`tput sgr0`
bold=$(tput bold)
black=`tput setaf 0`
red=`tput setaf 1`
green=`tput setaf 2`
blue=`tput setaf 4`
magenta=`tput setaf 5`
cyan=`tput setaf 6`
white=`tput setaf 7`

echo ${bold}
logo () {
echo -e """
 __ __  __ __  ____  ___     ____  ______    ___  ____  
|  |  ||  |  ||    \|   \   /    ||      |  /  _]|    \ 
|  |  ||  |  ||  o  )    \ |  o  ||      | /  [_ |  D  )
|  _  ||  |  ||   _/|  D  ||     ||_|  |_||    _]|    / 
|  |  ||  :  ||  |  |     ||  _  |  |  |  |   [_ |    \ 
|  |  ||     ||  |  |     ||  |  |  |  |  |     ||  .  |
|__|__| \__,_||__|  |_____||__|__|  |__|  |_____||__|\_|
                                                                       
                                    BY - Harshit Joshi\n
"""
}

clear
logo
echo -e "${green}\nFor Verbose Output And Command Used, View /root/hupdaterlog.txt\n"
echo -e "${red}\nUpdating Packages File\n"
logo > /root/hupdaterlog.txt
echo -e "Updating Packages File\n" >> /root/hupdaterlog.txt
echo -e "\nCommand Used ---> apt-get upgrade\n" >> /root/hupdaterlog.txt
sleep 3
apt-get update | tee -a /root/hupdaterlog.txt

clear
logo
echo -e "${green}\nUpgrading Important Packages\n"
echo -e "\nUpgrading Important Packages\n" >> /root/hupdaterlog.txt
echo -e "\nCommand Used ---> apt-get upgarde -y\n" >> /root/hupdaterlog.txt
sleep 3 
apt-get upgrade -y | tee -a /root/hupdaterlog.txt

clear
logo
echo -e "${blue}\nUpgrading All Packages\n"
echo -e "\nUpgrading All Packages\n" >> /root/hupdaterlog.txt
echo -e "\nCommand Used ---> apt-get dist-upgarde -y\n" >> /root/hupdaterlog.txt
sleep 3
apt-get dist-upgrade -y | tee -a /root/hupdaterlog.txt

clear
logo
echo -e "${white}\nRemoving Waste Or Old Packages\n"
echo -e "\nRemoving Waste And Old Packages\n" >> /root/hupdaterlog.txt
echo -e "\nCommand Used ---> apt-get autoremove\n" >> /root/hupdaterlog.txt
sleep 3
apt-get autoremove | tee -a /root/hupdaterlog.txt

clear
logo
echo -e "${magenta}\nUpdating Database\n"
echo -e "\nUpdating Database\n" >> /root/hupdaterlog.txt
echo -e "\nCommand Used ---> updatedb\n" >> /root/hupdaterlog.txt
sleep 3
updatedb
echo -e "\nDone\n" | tee -a /root/hupdaterlog.txt
sleep 3

clear
logo
echo -e "${yellow}\nRunning Check That All Packages Are Upgraded Or Not\n"
echo -e "\nRunning Check That All Packages Are Upgraded Or Not\n" >> /root/hupdaterlog.txt
echo -e "\nCommand Used ---> apt-get dist-upgrade -y\n" >> /root/hupdaterlog.txt
sleep 3
apt-get dist-upgrade -y | tee -a /root/hupdaterlog.txt

clear
logo
echo -e "${red}\nYou Are Now Fully Up To Date\n"
echo -e "${green}\nFor Verbose Output And Command Used, View /root/hupdaterlog.txt\n\n"
echo -n "${magenta}See /root/hupdaterlog.txt Now (y/n)?"
read answer
if [ "$answer" != "${answer#[Yy]}" ] ;then
    clear
    echo ${white}
    cat /root/hupdaterlog.txt
else
    echo -e "${white}\n\nExiting.....\n"
    sleep 2
    clear
fi
echo -e "${reset}"
